const options = [
  { value: "html", label: "HTML" },
  { value: "seo", label: "SEO" },
  { value: "css", label: "CSS" },
  { value: "sass", label: "Sass" },
  { value: "bootstrap", label: "Bootstrap" },
  { value: "git", label: "Git" },
  { value: "javascript", label: "JavaScript" },
  { value: "typescript", label: "TypeScript" },
  { value: "angular", label: "Angular" },
  { value: "vue", label: "Vue.js" },
  { value: "react", label: "React.js" },
  { value: "ract-native", label: "React Native" },
  { value: "redux", label: "Redux" },
  { value: "nodejs", label: "Node.js" },
  { value: "express", label: "Express.js" },
  { value: "nextjs", label: "Next.js" },
  { value: "mongodb", label: "Mongo DB" },
  { value: "mysql", label: "MySQL" },
  { value: "graphql", label: "GraphQL" },
  { value: "webserver", label: "Web Server" },
  { value: "pwa", label: "PWA" },
  { value: "php", label: "PHP" },
  { value: "python", label: "Python" },
  { value: "cplusplus", label: "C++" },
  { value: "unrealengine", label: "Unreal Engine" },
];

export default options;
